# ---[ Logging ]---
log_file = "dsb-rs.log"
log_level = "info"
# ---[ END: Logging ]---

# ---[ Server ]---
[server]
refetch_interval = 600 # in seconds, = 10 minutes
port = 8080
host = "127.0.0.1"
# ---[ END: Server ]---

# ---[ Providers ]---
# [school_providers]
# username = "username"
# password = "password"
# plan_title = "" # Name ("id") of the plan
# url_identifier = "identifier" # the url part, can be anything, but must be unique
[[school_providers]]
username = "187801"
password = "public"
plan_title = ""
url_identifier = "pub"
[[school_providers]]
username = "187801"
password = "public"
plan_title = ""
url_identifier = "pub2"
# ---[ END: Providers ]---

# ---[ Keys ]---
[keys]
enabled = true
allowed = ["xyz", "asdaslk"]
# ---[ END: Keys ]---